remote_theme: rundocs/jekyll-rtd-theme
title: Research Computing Services Franklin and Marshall College

nav_version: true
edit: false

readme_index:
  with_frontmatter: true

pages:
- Introduction:
  - Overview: 'README.md'
  - Current resources: 'overview/README.md'
- Accessing servers:
- Data storage and transfer:
- Using the cluster:
- Linux basics:
